"""
generate_patterns.py - Generates documentation pages in docs/ for difficulties, patterns, and complete numerical index.
"""

import os
from typing import List, Dict, Set
from common import ProblemInfo, TAG_TO_DOC_NAME, REQUIRED_PATTERNS, logger

def generate_doc_page(title: str, problems: List[ProblemInfo], out_dir: str) -> str:
    """Builds markdown content for a single difficulty or pattern page."""
    lines = []
    lines.append(f"# 🏷️ {title}")
    lines.append("")
    lines.append(f"**Total Problems Solved in this Category:** `{len(problems)}`")
    lines.append("")
    lines.append("[⬅️ Back to Portfolio README](../README.md) | [📚 All Problems (Sorted by ID)](AllProblems.md) | [📊 View Statistics](../stats/progress.md)")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("| Problem | Difficulty | Primary Tags | Solution Link | LeetCode Link |")
    lines.append("| :--- | :---: | :--- | :---: | :---: |")

    if not problems:
        lines.append("| *No problems solved yet in this category* | - | - | - | - |")
    else:
        # Sort problems numerically by ID
        sorted_probs = sorted(problems, key=lambda p: p.id)
        for p in sorted_probs:
            folder_rel = f"../{p.folder_name}/"
            prob_link = f"[{p.id}. {p.title}]({folder_rel})"
            tags_str = ", ".join(p.tags[:3]) if p.tags else "N/A"
            
            if p.solution_file:
                sol_link = f"[View Solution](../{p.solution_file})"
            else:
                sol_link = f"[View Folder]({folder_rel})"

            lc_link = f"[LeetCode Problem]({p.leetcode_url})"
            lines.append(f"| {prob_link} | {p.difficulty_badge} | {tags_str} | {sol_link} | {lc_link} |")

    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("<div align=\"center\">")
    lines.append("<i>Auto-generated by GitHub Actions LeetSync Workflow.</i>")
    lines.append("</div>")
    lines.append("")

    return "\n".join(lines)


def generate_all_problems_page(problems: List[ProblemInfo], out_dir: str) -> None:
    """Generates docs/AllProblems.md containing all problems sorted strictly by Problem ID numerically."""
    sorted_probs = sorted(problems, key=lambda p: p.id)
    lines = []
    lines.append("# 📚 All Problems (Sorted Numerically by Problem ID)")
    lines.append("")
    lines.append(f"**Total Problems Solved:** `{len(problems)}`")
    lines.append("")
    lines.append("[⬅️ Back to Portfolio README](../README.md) | [🟢 Easy](Easy.md) | [🟠 Medium](Medium.md) | [🔴 Hard](Hard.md) | [📊 View Statistics](../stats/progress.md)")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("| # | Problem Title | Difficulty | Algorithmic Tags | Solution Link | LeetCode Link |")
    lines.append("| --: | :--- | :---: | :--- | :---: | :---: |")

    for p in sorted_probs:
        folder_rel = f"../{p.folder_name}/"
        prob_link = f"[{p.id}. {p.title}]({folder_rel})"
        tags_str = ", ".join(p.tags) if p.tags else "N/A"
        
        if p.solution_file:
            sol_link = f"[View Solution](../{p.solution_file})"
        else:
            sol_link = f"[View Folder]({folder_rel})"

        lc_link = f"[LeetCode Problem]({p.leetcode_url})"
        lines.append(f"| {p.id} | {prob_link} | {p.difficulty_badge} | {tags_str} | {sol_link} | {lc_link} |")

    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("<div align=\"center\">")
    lines.append("<i>Auto-generated by GitHub Actions LeetSync Workflow.</i>")
    lines.append("</div>")
    lines.append("")

    content = "\n".join(lines)
    file_path = os.path.join(out_dir, "AllProblems.md")
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(content)


def generate_patterns(repo_root: str = ".", problems: List[ProblemInfo] = None) -> None:
    """Generates all difficulty, numerical index, and topic pattern markdown files inside docs/."""
    if problems is None:
        from common import scan_problems
        problems = scan_problems(repo_root)

    docs_dir = os.path.join(repo_root, "docs")
    os.makedirs(docs_dir, exist_ok=True)

    # 1. Generate AllProblems.md (Sorted by ID)
    generate_all_problems_page(problems, docs_dir)

    # 2. Difficulty Categorization
    easy_probs = [p for p in problems if p.difficulty == "Easy"]
    med_probs = [p for p in problems if p.difficulty == "Medium"]
    hard_probs = [p for p in problems if p.difficulty == "Hard"]

    diff_map = {
        "Easy": easy_probs,
        "Medium": med_probs,
        "Hard": hard_probs
    }

    for diff_name, prob_list in diff_map.items():
        content = generate_doc_page(f"{diff_name} Problems", prob_list, docs_dir)
        file_path = os.path.join(docs_dir, f"{diff_name}.md")
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(content)

    # 3. Pattern Categorization
    pattern_probs_map: Dict[str, List[ProblemInfo]] = {pat: [] for pat in REQUIRED_PATTERNS}

    for p in problems:
        matched_patterns: Set[str] = set()
        for tag in p.tags:
            doc_name = TAG_TO_DOC_NAME.get(tag)
            if doc_name:
                matched_patterns.add(doc_name)
            else:
                clean_tag = "".join(x.title() for x in tag.replace("-", " ").split())
                matched_patterns.add(clean_tag)

        for pat in matched_patterns:
            if pat not in pattern_probs_map:
                pattern_probs_map[pat] = []
            pattern_probs_map[pat].append(p)

    # Write all pattern docs
    for pat_name, prob_list in pattern_probs_map.items():
        content = generate_doc_page(f"{pat_name} Pattern", prob_list, docs_dir)
        file_path = os.path.join(docs_dir, f"{pat_name}.md")
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(content)

    logger.info(f"Successfully generated AllProblems.md and {len(diff_map) + len(pattern_probs_map)} pattern files in docs/.")


if __name__ == "__main__":
    generate_patterns(".")
