"""
generate_stats.py - Generates stats/progress.md with Mermaid pie chart, timeline, and growth analytics.
"""

from collections import defaultdict
import datetime
import os
from typing import List, Dict
from common import ProblemInfo, logger

def generate_stats(repo_root: str = ".", problems: List[ProblemInfo] = None) -> None:
    """Generates stats/progress.md analytics file."""
    if problems is None:
        from common import scan_problems
        problems = scan_problems(repo_root)

    stats_dir = os.path.join(repo_root, "stats")
    os.makedirs(stats_dir, exist_ok=True)

    total_solved = len(problems)
    easy_count = sum(1 for p in problems if p.difficulty == "Easy")
    medium_count = sum(1 for p in problems if p.difficulty == "Medium")
    hard_count = sum(1 for p in problems if p.difficulty == "Hard")

    easy_pct = (easy_count / total_solved * 100) if total_solved > 0 else 0
    med_pct = (medium_count / total_solved * 100) if total_solved > 0 else 0
    hard_pct = (hard_count / total_solved * 100) if total_solved > 0 else 0

    # Monthly and Weekly aggregations
    monthly_counts: Dict[str, int] = defaultdict(int)
    weekly_counts: Dict[str, int] = defaultdict(int)

    for p in problems:
        if p.date_added:
            try:
                dt = datetime.datetime.strptime(p.date_added, "%Y-%m-%d")
                month_key = dt.strftime("%Y-%m")
                week_key = dt.strftime("%Y-W%U")
                monthly_counts[month_key] += 1
                weekly_counts[week_key] += 1
            except ValueError:
                pass

    # Sort latest 20 problems by date_added desc, then problem ID desc
    latest_20 = sorted(problems, key=lambda p: (p.date_added, p.id), reverse=True)[:20]

    lines = []
    lines.append("# 📈 LeetCode Solutions Statistics & Analytics")
    lines.append("")
    lines.append("[⬅️ Back to Main README](../README.md) | [📚 View Topic Documentation](../docs/Easy.md)")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## 🏆 Overall Solved Summary")
    lines.append("")
    lines.append(f"- **Total Solved:** `{total_solved}`")
    lines.append(f"- 🟢 **Easy:** `{easy_count}` ({easy_pct:.1f}%)")
    lines.append(f"- 🟠 **Medium:** `{medium_count}` ({med_pct:.1f}%)")
    lines.append(f"- 🔴 **Hard:** `{hard_count}` ({hard_pct:.1f}%)")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## 📊 Difficulty Distribution (Mermaid Pie Chart)")
    lines.append("")
    lines.append("```mermaid")
    lines.append("pie title Problem Difficulty Breakdown")
    lines.append(f'    "Easy" : {easy_count}')
    lines.append(f'    "Medium" : {medium_count}')
    lines.append(f'    "Hard" : {hard_count}')
    lines.append("```")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## 🗓️ Monthly Growth")
    lines.append("")
    lines.append("| Month | Problems Solved | Cumulative Total |")
    lines.append("| :---: | :---: | :---: |")

    cum_total = 0
    for m_key in sorted(monthly_counts.keys()):
        cnt = monthly_counts[m_key]
        cum_total += cnt
        lines.append(f"| {m_key} | {cnt} | {cum_total} |")

    if not monthly_counts:
        lines.append("| *No timestamp data available* | - | - |")

    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## 📅 Recent Weekly Growth")
    lines.append("")
    lines.append("| Week | Problems Solved |")
    lines.append("| :---: | :---: |")

    # Show last 10 active weeks
    sorted_weeks = sorted(weekly_counts.keys(), reverse=True)[:10]
    for w_key in reversed(sorted_weeks):
        lines.append(f"| {w_key} | {weekly_counts[w_key]} |")

    if not weekly_counts:
        lines.append("| *No timestamp data available* | - |")

    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## 🕒 Latest 20 Solved Problems")
    lines.append("")
    lines.append("| # | Problem Title | Difficulty | Primary Tags | Solution Link | Date Added |")
    lines.append("| :---: | :--- | :---: | :--- | :---: | :---: |")

    for p in latest_20:
        folder_rel = f"../{p.folder_name}/"
        prob_link = f"[{p.id}. {p.title}]({folder_rel})"
        tags_str = ", ".join(p.tags[:3]) if p.tags else "N/A"
        
        if p.solution_file:
            sol_link = f"[View Solution](../{p.solution_file})"
        else:
            sol_link = f"[View Folder]({folder_rel})"

        lines.append(f"| {p.id} | {prob_link} | {p.difficulty_badge} | {tags_str} | {sol_link} | {p.date_added} |")

    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("<div align=\"center\">")
    lines.append("<i>Auto-generated by GitHub Actions LeetSync Workflow.</i>")
    lines.append("</div>")
    lines.append("")

    content = "\n".join(lines)
    file_path = os.path.join(stats_dir, "progress.md")
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(content)

    logger.info("Successfully generated stats/progress.md.")


if __name__ == "__main__":
    generate_stats(".")
